### ISSUE TITLE
Font Size Small On Bootstrap 3.3

### ISSUE THREAD

**Issue by cyberzilla** [fengyuanchen/pickerjs#29]
how to fix it, i get pickerjs small size on bootstrap 3.3

![Screenshot (1)](https://user-images.githubusercontent.com/1154922/58074308-8c16cb80-7bd7-11e9-9731-ba2767d212ad.png)

**Comment by dormidosan** [comment]
I got same bug, how do you resolved it ?

**Comment by fengyuanchen** [comment]
Just override the built-in font size:

```css
.picker {
  /* font-size: 1rem; */
  font-size: 16px;
}
```
